# Generated by Django 6.0 on 2026-04-23 05:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0002_add_community_permission_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(
                blank=True,
                related_name='community_liked_posts',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]