# Generated by Django 6.0.4 on 2026-05-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0002_add_community_permission_fields'),
        ('communityapp', '0002_repair_follow_status_column'),
    ]

    operations = [
    ]
