# Generated by Django 6.0.4 on 2026-05-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0004_alter_post_likes_alter_reply_post'),
        ('communityapp', '0004_repair_creator_memberships'),
    ]

    operations = [
    ]
