# Generated by Django 6.0.4 on 2026-05-18 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communityapp', '0003_merge_20260505_1225'),
        ('communityapp', '0005_merge_20260506_1138'),
        ('communityapp', '0005_merge_20260506_1219'),
    ]

    operations = [
    ]
